# Generated by Django 4.2.7 on 2024-01-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_in_stock_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
